// <auto-generated />
namespace TB181979_Desafio03.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MigracionTres : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MigracionTres));
        
        string IMigrationMetadata.Id
        {
            get { return "202111130313384_MigracionTres"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
